# Generated by Django 5.2.9 on 2026-01-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('medication', 'Medication'), ('salaries', 'Salaries'), ('others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='goat',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='goat',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='goat',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goat',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('sold', 'Sold'), ('dead', 'Dead')], default='alive', max_length=10),
        ),
        migrations.AlterField(
            model_name='goat',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('number_of_kids', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('mother_goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='births', to='goats.goat')),
            ],
        ),
        migrations.AlterField(
            model_name='goat',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goats.breed'),
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('condition', models.CharField(max_length=255)),
                ('treatment', models.TextField()),
                ('vaccine_administered', models.CharField(blank=True, max_length=100, null=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='goats.goat')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('sale_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goats.goat')),
            ],
        ),
    ]
