# Generated by Django 5.2.9 on 2026-01-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0002_breed_expense_purchase_remove_goat_health_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='breed',
            field=models.CharField(choices=[('somali', 'Somali'), ('galla', 'Galla'), ('giriama', 'Giriama'), ('mixed', 'Mixed Breed')], default='mixed', max_length=20),
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
